name: Generate XMLTV EPG

on:
  # Run on the 1st day of every month at midnight UTC (Monthly update cycle)
  schedule:
    - cron: '0 0 1 * *'
  # Allow manual trigger from the GitHub Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    # ----------------------------------------------------
    # FIX: Add permissions to allow the bot to write/commit files
    # ----------------------------------------------------
    permissions:
      contents: write 

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      # Need full history for the commit action
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Execute EPG Parser Script
      # This runs the script which reads all .txt files and creates epg.xml
      run: |
        python epg_parser.py
        
    # ----------------------------------------------------
    # FIX: Force Pull to prevent 'divergence' error before commit
    # ----------------------------------------------------
    - name: Pull before commit (to avoid divergence)
      run: git pull

    - name: Commit and Push Changes
      # Uses a third-party action to automatically commit and push the new file
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Removed the 'token: ${{ secrets.GITHUB_TOKEN }}' input as it is 
        # redundant and causes a warning in v5 of this action. 
        # The permission is already granted via the 'permissions: contents: write' block.
        
        # Commit only the generated XML file
        file_pattern: 'epg.xml'
        commit_message: "Auto-generated EPG update for 28 days"
        # Optional: Set author for a cleaner commit history
        commit_author: 'GitHub Actions <actions@github.com>'
        # Recommended: Ensures the commit action can push to the branch
        commit_options: '--no-verify'
